### ISSUE TITLE
Image-service URL should be set via config

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/images-client-plugin#11]
https://github.com/AtlasOfLivingAustralia/images-client-plugin/blob/master/web-app/js/ala-image-viewer.js#L14

`var imageServiceBaseUrl = "https://images.ala.org.au";`

hard-coded currently. Should be set via config.

**Comment by djtfmartin** [comment]
Default is still https://images.ala.org.au, but this is overridden using options.
