### ISSUE TITLE
hide gallery bottom div when there is only one image

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/images-client-plugin#9]
hide gallery bottom div when there is only one image and make full use of the screen real estate.

![screenshot 2015-06-18 09 58 06](https://cloud.githubusercontent.com/assets/444897/8227666/217ede3e-15a1-11e5-9a55-54724fa22ebb.jpg)

**Comment by aruizca** [comment]
@djtfmartin That is something that have to be done in the host app. Do you want me to do this in taxonoverflow?

**Comment by djtfmartin** [comment]
im not sure this is relevant any more.
